<script>
	import CodeEditor from '$lib/CodeEditor.svelte';
	import { onMount } from 'svelte';

	// Example code to display
	let code = $state(`-- Lua example
local x = 5
local y = 10
local sum = x + y
print("Sum:", sum)

if sum > 10 then
  print("Sum is greater than 10")
else
  print("Sum is 10 or less")
end`);

	// LSP tokens will be automatically generated by the silt-lua LSP
	let lspTokens = $state([]);

	let output = $state('');
	let wasmInitialized = $state(false);
	let siltInit = null;
	let siltRun = null;

	onMount(async () => {
		// Dynamically import silt-lua if available
		try {
			const siltModule = await import('silt-lua');
			siltInit = siltModule.init;
			siltRun = siltModule.run;
		} catch (e) {
			console.warn("silt-lua not available:", e);
			return;
		}

		try {
			await siltInit();
			wasmInitialized = true;
			console.log("WASM initialized in page");
		} catch (e) {
			console.error("WASM initialization failed:", e);
		}
	});

	function handleCodeChange(newValue) {
		code = newValue;
	}

	function runCode() {
		if (!wasmInitialized || !siltRun) {
			output = "Error: WASM not initialized or silt-lua not available";
			return;
		}

		try {
			const result = siltRun(code);
			output = result || "(no output)";
		} catch (e) {
			output = `Error: ${e instanceof Error ? e.message : 'Unknown error'}`;
		}
	}
</script>

<svelte:head>
	<title>Simple Code Editor</title>
</svelte:head>

<main>
	<div class="container">
		<header>
			<h1>Simple Code Editor</h1>
			<p>A barebones Svelte code editor with LSP-based syntax highlighting</p>
		</header>

		<div class="editor-section">
			<div class="editor-header">
				<h2>Code Editor</h2>
				<button onclick={runCode} class="run-button">▶ Run</button>
			</div>
			<p class="hint">Try copying and pasting code! The plain text is editable while syntax highlighting overlays perfectly.</p>
			<CodeEditor 
				initialValue={code} 
				lspPayload={lspTokens}
				onValueChange={handleCodeChange}
			/>
		</div>

		{#if output}
			<div class="output-section">
				<h2>Output</h2>
				<pre class="output-window">{output}</pre>
			</div>
		{/if}

		<div class="info-section">
			<h3>Supported Token Types</h3>
			<div class="token-grid">
				<div class="token-example"><span class="token-keyword">keyword</span></div>
				<div class="token-example"><span class="token-string">string</span></div>
				<div class="token-example"><span class="token-number">number</span></div>
				<div class="token-example"><span class="token-operator">operator</span></div>
				<div class="token-example"><span class="token-bool">bool</span></div>
				<div class="token-example"><span class="token-nil">nil</span></div>
				<div class="token-example"><span class="token-comment">comment</span></div>
			</div>
		</div>
	</div>
</main>

<style>
	:global(body) {
		margin: 0;
		padding: 0;
		font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, sans-serif;
		background: #f0f2f5;
		color: #1a1a1a;
	}

	main {
		padding: 20px;
		max-width: 1400px;
		margin: 0 auto;
	}

	.container {
		display: flex;
		flex-direction: column;
		gap: 30px;
	}

	header {
		text-align: center;
		padding: 20px 0;
	}

	h1 {
		margin: 0 0 10px 0;
		font-size: 2.5rem;
		color: #2d3748;
		font-weight: 700;
	}

	h2 {
		margin: 0 0 12px 0;
		font-size: 1.5rem;
		color: #2d3748;
		font-weight: 600;
	}

	h3 {
		margin: 0 0 16px 0;
		font-size: 1.2rem;
		color: #2d3748;
		font-weight: 600;
	}

	header p {
		margin: 0;
		font-size: 1.1rem;
		color: #718096;
	}

	.editor-section {
		background: white;
		padding: 24px;
		border-radius: 12px;
		box-shadow: 0 2px 8px rgba(0, 0, 0, 0.08);
	}

	.editor-header {
		display: flex;
		justify-content: space-between;
		align-items: center;
		margin-bottom: 12px;
	}

	.editor-header h2 {
		margin: 0;
	}

	.run-button {
		background: #48bb78;
		color: white;
		padding: 8px 16px;
		border: none;
		border-radius: 6px;
		font-size: 0.95rem;
		font-weight: 500;
		cursor: pointer;
		transition: background 0.2s;
		display: flex;
		align-items: center;
		gap: 4px;
	}

	.run-button:hover {
		background: #38a169;
	}

	.run-button:active {
		background: #2f855a;
	}

	.output-section {
		background: white;
		padding: 24px;
		border-radius: 12px;
		box-shadow: 0 2px 8px rgba(0, 0, 0, 0.08);
	}

	.output-window {
		background: #f7fafc;
		border: 1px solid #e2e8f0;
		border-radius: 6px;
		padding: 16px;
		margin: 0;
		font-family: 'Consolas', 'Monaco', monospace;
		font-size: 13px;
		line-height: 1.5;
		white-space: pre-wrap;
		word-wrap: break-word;
		overflow-x: auto;
		max-height: 300px;
		overflow-y: auto;
	}

	.info-section {
		background: white;
		padding: 24px;
		border-radius: 12px;
		box-shadow: 0 2px 8px rgba(0, 0, 0, 0.08);
	}

	.hint {
		margin: 0 0 16px 0;
		color: #718096;
		font-size: 0.95rem;
	}

	button {
		background: #4299e1;
		color: white;
		padding: 10px 20px;
		border: none;
		border-radius: 6px;
		font-size: 1rem;
		font-weight: 500;
		cursor: pointer;
		transition: background 0.2s;
	}

	button:hover {
		background: #3182ce;
	}

	button:active {
		background: #2c5282;
	}

	.token-grid {
		display: grid;
		grid-template-columns: repeat(auto-fill, minmax(150px, 1fr));
		gap: 12px;
	}

	.token-example {
		padding: 12px;
		background: #f7fafc;
		border-radius: 6px;
		text-align: center;
		font-family: 'Consolas', 'Monaco', monospace;
		font-size: 14px;
		border: 1px solid #e2e8f0;
	}

	@media (prefers-color-scheme: dark) {
		:global(body) {
			background: #1a202c;
			color: #e2e8f0;
		}

		h1, h2, h3 {
			color: #f7fafc;
		}

		header p, .hint {
			color: #a0aec0;
		}

		.editor-section,
		.info-section,
		.output-section {
			background: #2d3748;
		}

		.output-window {
			background: #1a202c;
			border-color: #4a5568;
			color: #e2e8f0;
		}

		.token-example {
			background: #1a202c;
			border-color: #4a5568;
		}
	}
</style>
